trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm install -g npm@latest
    displayName: 'Update npm to latest version'

  - script: npm install
    displayName: 'Install npm dependencies'

  - script: npm run build
    displayName: 'Build the project'
