version: '3'
services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: taief
      MONGO_INITDB_ROOT_PASSWORD: OLbREgM8bj97e9pX
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-stack

  # Backend Service (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '7001:7000'  # Change host port for backend
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/foodordering?authSource=admin
      NODE_ENV: development
      PORT: 5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-stack

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3001:3000'  # Change host port for frontend
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_API_URL: http://backend:7000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-stack

# Networks
networks:
  mern-stack:
    driver: bridge

# Volumes
volumes:
  mongo-data:
